# Generated by Django 3.2.9 on 2022-02-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(default='', max_length=50)),
                ('party_symbol', models.ImageField(default='', upload_to='party_symbols')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='head_shot',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
