# Generated by Django 3.2.9 on 2022-02-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0002_auto_20220224_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='description',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
