# Generated by Django 3.2.9 on 2022-02-25 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ovs', '0003_auto_20220225_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('party_name', models.CharField(default='', max_length=50)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.RenameModel(
            old_name='Voting',
            new_name='Party',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='party',
            new_name='party_name',
        ),
    ]
