# Generated by Django 3.2.9 on 2022-02-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0004_auto_20220225_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='head_shot',
            field=models.ImageField(blank=True, upload_to='static/users/profile_images'),
        ),
    ]
