# Generated by Django 3.2.9 on 2022-02-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0005_alter_userprofile_head_shot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='party_symbol',
            field=models.ImageField(default='', upload_to='static/Party/party_symbols'),
        ),
    ]
