# Generated by Django 3.2.9 on 2022-02-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0006_alter_party_party_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='head_shot',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
