# Generated by Django 3.2.9 on 2022-02-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0007_alter_userprofile_head_shot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='party_symbol',
            field=models.ImageField(default='', upload_to='party_symbols'),
        ),
    ]
