# Generated by Django 3.2.9 on 2022-02-25 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0008_alter_party_party_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='party_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ovs.party'),
        ),
    ]
