# Generated by Django 3.2.9 on 2022-02-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0009_alter_vote_party_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='party_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
