# Generated by Django 3.2.12 on 2022-03-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0011_userprofile_vid'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vid',
            field=models.CharField(default='TWG1094271', max_length=11),
        ),
    ]
