# Generated by Django 3.2.9 on 2022-03-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0012_auto_20220310_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vid',
            field=models.CharField(default='ITL8379154', max_length=11),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
