# Generated by Django 3.2.9 on 2022-03-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0014_alter_userprofile_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='vid',
            field=models.CharField(default='MZM6764299', max_length=11),
        ),
    ]
